host { 'hosts test':
    name           => 'testing.puppetlabs.vm', # (namevar) The host...
    ensure         => 'present', # The basic property that the resource should be...
    comment        => 'This is a test server', # A comment that will be attached to the line with 
    host_aliases   => 'testing', # Any aliases the host might have.  Multiple...
    ip             => '127.0.0.1', # The host's IP address, IPv4 or...
    provider       => 'parsed', # The specific backend to use for this `host...
    target         => '/etc/hosts', # The file in which to store service information.  
}
